<main>

    <div class="marketing-cours">



        <div class="marketing-contenu">

            <div class="etude-de-marche">

                <div class="hide">
                    <a class="changeType" href="#pestel" data-type="pestel">Pestel</a>
                    <a class="changeType" href="#swot" data-type="swot">SWOT</a>
                    <a class="changeType" href="#ciblage" data-type="ciblage">Ciblage</a>

                    <div id="pestel">
                        <section class="pestel">

                            <article class="definition">

                                <h1 class="titre-definition"> PESTEL</h1>
                                <p class="texte-definition"> En stratégie d'entreprise, l'analyse PESTEL (Politique, Économique, Sociologique, Technologique, Écologique, Légal) est un modèle permettant d'identifier l'influence (positive ou négative) que peuvent exercer, sur une organisation, les facteurs macro-environnementaux. L'analyse PESTEL ou PESTE n'est cependant pas un outil mais bien une aide mnémotechnique qui permet d'effectuer une analyse externe plus simplement et ainsi de réaliser une matrice <a href="#"> SWOT </a>.</p>

                            </article>

                            <article class="principe">

                                <p class=""> Le modèle PESTEL distingue six catégories d'influences macro-environnementales qui peuvent influencer une industrie. Il s'agit des facteurs :</p>

                                <li>Politiques : stabilité gouvernementale, politique fiscale, protection sociale, commerce extérieur</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p>L’entrée en vigueur d’une nouvelle loi augmentant la taxation des entreprises est un facteur négatif qui va alourdir les charges de la société ; il s’agit donc d’une menace.</p>
                                    </div>
                                </div>



                                <li>Économiques : cycle économique, évolution du PNB, taux d'intérêt, politique monétaire, inflation, chômage, revenu disponible, etc.</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p>Une diminution marquée du pouvoir d’achat de la population peut avoir un impact variable sur l’entreprise, en fonction notamment du niveau de prix de ses produits.</p>
                                    </div>

                                </div>


                                <li>Sociologique : démographie, distribution des revenus, mobilité sociale, consumérisme, niveau d'éducation, attitude de loisir et de travail, etc.</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p>Une baisse du taux de natalité peut avoir des conséquences néfastes pour une entreprise vendant des produits pour nourrissons ou jeunes enfants (couches, poussettes, etc.)</p>
                                    </div>
                                </div>





                                <li>Technologiques : dépenses publiques en R & D, investissements privés sur la technologie, nouveaux brevets ou découvertes, vitesse de transfert technologique, taux d'obsolescence, etc.</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p>Un brevet récemment déposé par un concurrent peut signifier qu’il va prochainement dévoiler une innovation importante, ce qui menacerait votre entreprise.</p>
                                    </div>
                                </div>




                                <li>Écologiques : lois sur la protection de l'environnement, retraitement des déchets, consommation d'énergie, etc.</li>


                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p>L’amélioration de l’isolation thermique des logements engendre une diminution de la consommation d’électricité, de gaz ou de fioul, ce qui peut menacer les producteurs d’énergie.</p>
                                    </div>
                                </div>


                                <li>Légaux : lois sur les monopoles, droit du travail, législation sur la santé, normes de sécurité, etc.</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p>Une norme de sécurité peut obliger l’entreprise à réaliser d’importants investissements pour la respecter.</p>
                                    </div>
                                </div>

                            </article>


                            <article class="schema">
                                <img src="<?= $wwwUrl ?>/images/pestel.png" alt="">
                            </article>


                            <article class="video-pestel">
                                <div><iframe width="560" height="315" src="https://www.youtube.com/embed/UPY79_f8Iuk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                            </article>

                            <article class="aller-plus-loin">

                                <div class="livre">

                                    <a href="https://www.amazon.fr/Mod%C3%A8le-PESTEL-Analyser-environnement-anticiper/dp/2806264154/ref=sr_1_1?s=books&ie=UTF8&qid=1550064263&sr=1-1&keywords=Pestel">
                                        <h3 titre-livre> Les livres : </h3>

                                        <p>Gestion & marketing numéro 28 l'analyse pestel et le macroenvironnement </p>
                                    </a>

                                </div>


                                <div class="article-site">
                                    <h3 titre-articles-sites> Ils en parlent : </h3>
                                    <a href="https://www.creer-mon-business-plan.fr/actualites/les-outils-danalyse-strategique-de-lentreprise-analyse-pestel.html">
                                        <p> Analyse Pestel</p>
                                    </a>
                                    <a href="https://www.codeur.com/blog/analyse-pestel/">
                                        <p>Comment faire une analyse PESTEL ?</p>
                                    </a>

                                </div>

                            </article>

<form class="generic-form" action="<?=$requestUrl?>/comment" method="POST">

    <input type="hidden" >

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <ul>
            <li>
                <label for="pseudo">Pseudo :</label>
                <input type="text" id="pseudo" name="pseudo">
            </li>
            <li>
                <label class="textarea" for="comments">Commentaire :</label>
                <textarea id="contents" name="contents" rows="5"></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>

  <hr>
       <div id="comments">
    </div> 
                                                 
                        </section>
                    </div>

                    <div id="swot">
                        <section class="swot">

                            <article class="definition">

                                <h1 class="titre-definition"> SWOT</h1>
                                <p class="texte-definition">

                                </p>

                            </article>

                            <article class="principe">

                                <p class=""> </p>

                                <li>Strengths (Force) : </li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>
                                </div>



                                <li>Weaknesses (faiblesses) : .</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>

                                </div>


                                <li>Opportunities (opportunités) : </li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>
                                </div>




                                <li>Threats (menaces) : </li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>
                                </div>


                            </article>


                            <article class="schema">
                                <img src="<?= $wwwUrl ?>/images/swot.png" alt="">
                            </article>


                            <article class="video-swot">
                                <div><iframe width="560" height="315" src="https://www.youtube.com/embed/SN7AX--FCYU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                            </article>

                            <article class="allerPlusLoin">

                                <div class="livre">

                                    <a href="https://www.amazon.fr/Matrice-SWOT-strat%C3%A9gique-entreprise-Marketing-ebook/dp/B0156J36LO">
                                        <h3 titre-livre> Les livres : </h3>

                                        <p>La Matrice SWOT: Élaborer un plan stratégique pour votre entreprise </p>
                                    </a>

                                </div>


                                <div class="article-site">
                                    <h3 titre-articles-sites> Ils en parlent : </h3>
                                    <a href="https://www.creer-mon-business-plan.fr/actualites/les-outils-danalyse-strategique-de-lentreprise-matrice-swot.html">
                                        <p> Analyse SWOT</p>
                                    </a>
                                    <a href="#">
                                        <p>Comment faire un SWOT ?</p>
                                    </a>

                                </div>

                            </article>

                        
                       
                        </section>

                    </div>

                    <div id="ciblage">
                        <section class="ciblage">

                            <article class="definition">

                                <h1 class="titre-definition"> ciblage</h1>
                                <p class="texte-definition">

                                </p>

                            </article>

                            <article class="principe">

                                <p class=""> </p>

                                <li>Strengths (Force) : </li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>
                                </div>



                                <li>Weaknesses (faiblesses) : .</li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>

                                </div>


                                <li>Opportunities (opportunités) : </li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>
                                </div>




                                <li>Threats (menaces) : </li>

                                <div class="su-box su-box-style-default" style="border-color:#2d7aaa;border-radius:3px">
                                    <div class="su-box-title" style="background-color:#3898d4 ;color:#FFFFFF;border-top-left-radius:1px;border-top-right-radius:1px">Exemple :</div>
                                    <div class="su-box-content su-clearfix" style="border-bottom-left-radius:1px;border-bottom-right-radius:1px">
                                        <p> </p>
                                    </div>
                                </div>


                            </article>


                            <article class="schema">
                                <img src="<?= $wwwUrl ?>/images/swot.png" alt="">
                            </article>


                            <article class="video-swot">
                                <div><iframe width="560" height="315" src="https://www.youtube.com/embed/SN7AX--FCYU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
                            </article>

                            <article class="allerPlusLoin">

                                <div class="livre">

                                    <a href="https://www.amazon.fr/Matrice-SWOT-strat%C3%A9gique-entreprise-Marketing-ebook/dp/B0156J36LO">
                                        <h3 titre-livre> Les livres : </h3>

                                        <p>La Matrice SWOT: Élaborer un plan stratégique pour votre entreprise </p>
                                    </a>

                                </div>


                                <div class="article-site">
                                    <h3 titre-articles-sites> Ils en parlent : </h3>
                                    <a href="https://www.creer-mon-business-plan.fr/actualites/les-outils-danalyse-strategique-de-lentreprise-matrice-swot.html">
                                        <p> Analyse SWOT</p>
                                    </a>
                                    <a href="#">
                                        <p>Comment faire un SWOT ?</p>
                                    </a>

                                </div>

                            </article>

                        </section>


                    </div>
                    

                </div>
 
            
            </div>

        </div>

    </div>

</main>

    
<script src="<?=$wwwUrl?>/js/classes/Comment.class.js"></script>
