<main>

    <div class="marketing-cours">



        <div class="marketing-contenu">



           
        <div class="strategie">

            <section id="positionnement">

                <article class="definition"> </article>

                <article class="principe"> </article>

                <article class="schema"></article>

                <article class="video-positionement"> </article>

                <article class="aller-plus-loin"> </article>

            </section>





            <section id="cycle-produit">

                <article class="definition"> </article>

                <article class="principe"> </article>

                <article class="schema"></article>

                <article class="video-cycle-produit"> </article>

                <article class="aller-plus-loin"> </article>

            </section>



        </div>


        <div class="plan-action">

                   <section id="distribution">

                <article class="definition"> </article>

                <article class="principe"> </article>

                <article class="schema"></article>

                <article class="video-distribution"> </article>

                <article class="aller-plus-loin"> </article>

            </section>


                <section id="communication">

                <article class="definition"> </article>

                <article class="principe"> </article>

                <article class="schema"></article>

                <article class="video-communication"> </article>

                <article class="aller-plus-loin"> </article>

            </section>





        </div>

  

        </div>

    </div>

</main>

