<div>

    <ul class="tabs">
        <li class="active"><a href="#home">Marketing</a></li>
        <li><a href="#mentions">Business</a></li>
        <li><a href="#about">Technology</a></li>
    </ul>

    <div class="tabs-content">

        <div class="tab-content active" id="home">

            <div class="contenu-cours">


                <div class="cours">

                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours">
                        <ul>
                            <a href="#">
                                <h1> Etude de marche </h1>
                            </a>
                            <a href="#">
                                <li>Pestel</li>
                            </a>
                            <a href="#">
                                <li>SWOT</li>
                            </a>
                        </ul>
                    </div>

                </div>

                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours">
                        <ul>
                            <h1> Strategie Marketing </h1>
                            <a href="#">
                                <li>Positionnement</li>
                            </a>
                            <a href="#">
                                <li>Cycle de vie d'un produit</li>
                            </a>
                        </ul>
                    </div>
                </div>

                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours">
                        <ul>
                            <h1>Plan d'action</h1>
                            <a href="#">
                                <li>Distribution</li>
                            </a>
                            <a href="#">
                                <li>Promotion</li>
                            </a>
                            <a href="#">
                                <li>Communication</li>
                            </a>
                        </ul>
                    </div>
                </div>

                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>





            </div>

        </div>
        <div class="tab-content" id="mentions">


            <div class="contenu-cours">



                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>


                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>



                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>





            </div>


        </div>
        <div class="tab-content" id="about">
            <div class="contenu-cours">



                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>


                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>



                <div class="cours">
                    <div class="image-cours"><a href=""> <img src="<?= $wwwUrl ?>/images/logo.png" width="250" alt="" /></a> </div>
                    <div class="details-cours"> </div>
                </div>





            </div>
        </div>

    </div>
    <script src="<?=$wwwUrl?>/js/navigation.js"></script>
</div>
