

<div class="contenaireProduits">


    <div class="produits">
       <a href="<?=$requestUrl?>/coque/details">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>
<div class="produits">
       <a href="#">
        <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="250" alt="">
        <div class="descriptionProduits">
            <p>Coque iPhone APPLE COQUE EN CUIR POUR IPHONE 8 / 7 - ROUGE</p>
        </div>
        <div class="prixProduits">
            <p> 1€</p>
        </div>
        </a>
    </div>







</div>


<!--
<table class="generic-table products-list">

    <caption>Coque</caption>

    <tbody>

    	<?php foreach($coques as $coque): ?>

          <tr>

            <td>
              <img src="<?= $wwwUrl ?>/images/meals/<?= $coque['Photo']; ?>" alt="<?= $coque['Name']; ?>">
            </td>

            <td>
                <strong><?= $coque['Name']; ?></strong>
                    <p><coque['Description']; ?></p>
            </td>

            <td class="number"><strong><?= number_format($coque['SalePrice'], 2) ?></strong> €
            </td>

          </tr>
        <?php endforeach; ?>

    </tbody>
</table>
-->
