
<form action="<?=$requestUrl?>/charge?orderId=<?=$orderId?>" method="post" id="payment-form" class="generic-form">
	<div class="form-row">


	 <div id="card-element" class="form-control ">
			      <!-- A Stripe Element will be inserted here. -->
	</div>

			    <!-- Used to display form errors. -->
	<div id="card-errors" role="alert"></div>
	</div>

	<button class="button button-primary" >Submit Payment</button>
</form>
<script src="https://js.stripe.com/v3/"></script>
<script src="<?=$wwwUrl?>/js/charge.js"></script>
