<main>

    <form action="<?=$requestUrl?>/user/register" method="POST">

        <fieldset>
            <legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
            <ul>
                <li>
                    <label for="nom">Nom:</label>
                    <input id="nom" type="text" name="nom" data-required data-name="firstName" value="">
                </li>

                <li>
                    <label for="prenom">Nom:</label>
                    <input id="prenom" type="text" name="prenom" data-required data-name="lastName" value="">
                </li>


                <li>
                    <label for="email">E-mail :</label>
                    <input id="email" type="text" name="email" data-required data-name="E-mail" value="">
                </li>

                <li>
                    <label for="password">Mot de passe :</label>
                    <input id="password" type="password" name="password" data-required data-name="Mot de passe" data-length="8">
                </li>
            </ul>
        </fieldset>

        <ul>
            <li>
                <input class="button button-primary" type="submit" value="Créer le compte">
            </li>
        </ul>
    </form>

</main>
