<main>

    <div class="marketing-cours">



        <div class="marketing-contenu">





        <div class="plan-action">

                   <section id="distribution">

                <article class="definition"> </article>

                <article class="principe"> </article>

                <article class="schema"></article>

                <article class="video-distribution"> </article>

                <article class="aller-plus-loin"> </article>

            </section>


                <section id="communication">

                <article class="definition"> </article>

                <article class="principe"> </article>

                <article class="schema"></article>

                <article class="video-communication"> </article>

                <article class="aller-plus-loin"> </article>

            </section>





        </div>

   
        </div>

    </div>

</main>

