<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

<div class="responsive">

    <div> <a href="#"> <img src="<?= $wwwUrl ?>/images/coque/coque1.jpg" width="150" alt="" /></a></div>
    
    <div> <a href="#"> <img src="<?= $wwwUrl ?>/images/coque/coque1details/1.jpg" width="150" alt="" /></a></div>  
    
    <div> <a href="#"> <img src="<?= $wwwUrl ?>/images/coque/coque1details/2.jpg" width="150" alt="" /></a></div>
    
   
</div>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<script type="text/javascript">
    $('.responsive').slick({
        dots: true,
        infinite: false,
        speed: 300,
        slidesToShow: 4,
        slidesToScroll: 4,
        responsive: [{
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    infinite: true,
                    dots: true
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                }
            }
            // You can unslick at a given breakpoint now by adding:
            // settings: "unslick"
            // instead of a settings object
        ]
    });

</script>
