<form class="generic-form" action="edit_post.php" method="post">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="<?= $_GET['id'] ?>">

    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="<?= htmlspecialchars($post['Title']) ?>">
            </li>
            <li>
                <label class="textarea" for="content">Article :</label>
                <textarea id="content" name="content" rows="15"><?= htmlspecialchars($post['Content']) ?></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Mettre à jour</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>