
<h2><i class="fa fa-home"></i> Accueil</h2>

<ul class="post-list">
    <?php foreach($posts as $post): ?>
        <li class="post">
            <h3>
                <i class="fa fa-hand-o-right"></i>&nbsp;
                <!-- Lien vers article de blog détaillé avec les commentaires -->
                <a href="show_post.php?id=<?= intval($post['Id']) ?>" title="Consulter l'article"> <!-- id du post  -->
                    <?= htmlspecialchars($post['Title']) ?>
                </a>
            </h3>
            <!-- Seul un extrait de l'article du blog est affiché -->
            <article><?= substr(htmlspecialchars($post['Content']), 0, 100) ?>&nbsp;[...]</article>
            <small>
                Rédigé par <?= htmlspecialchars($post['FirstName']) ?> <?= htmlspecialchars($post['LastName']) ?>
                le <?= htmlspecialchars($post['CreationDate']) ?>
            </small>
        </li>
    <?php endforeach; ?>
</ul>
