<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">
</head>

<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
        <nav>
          <?php if(array_key_exists('role', $_SESSION) == true )
          { ?>
            <?php if($_SESSION['role'] == 'admin') { ?>
              <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
            <?php } ?>
            <a href="deco.php"><i class="fa fa-cogs"></i>Deconnection</a>
          <?php } else {?>
            <a href="register.php"> <i class="fa fa-cogs"></i>register</a>
           	<a href="login.php"><i class="fa fa-cogs"></i>Login</a>
          <?php } ?>
<!-- AFFICHACHE EN FONCTION DES ROLES : pour le profil user = consultation+ajout de commentaire nav(Deconnection). Profil admin =consultation+ajout de commentaire +ajout/suppresion / modification des posts+  nav(Deconnection+Administration(espace)   -->
        </nav>
    </header>

    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $template.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>
</body>
</html>
