
<h2><i class="fa fa-pencil"></i> Connectez vous </h2>

<?php if ($error == true ) {?>
<div class="popup">
    <p> <?= $message ?></p>
</div>
<?php } ?>
<!-- affiche un message si probleme de CONNECTION -->


<form action="login.php" method="post">

	<input type="text" placeholder="mail" name="mail"/>

	<input type="password" placeholder="password" name="password"/>

	<input type="submit" value="connect"/>

</form>
