<main>
    <!-- Affichage du template lié à la vue -->
    <h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" action="<?=$requestUrl?>/user/login" method="POST">



	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="email">E-mail :</label>
				<input id="email" type="text" name="email" data-required data-name="E-mail" value="">
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input id="password" type="password" name="password" data-required data-name="Mot de passe">
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Connexion">
			<a class="button button-cancel small" href="<?=$requestUrl?>">Annuler</a>
		</li>
	</ul>
</form>

</main>
