<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="traducteur.css">
</head>

<body>

    <header>
        <h1>Traducteur Anglais - Français </h1>

    </header>
    <main>

        <form action="traducteur.php" method="post">

            <input name="word" type="text" />
            
            <input type="submit" value="Traduire" />

            <ul>
                <li><select name="langue" id="traduire">
                        <option value="anglais">Francais vers Anglais</option>
                        <option value="francais">Anglais vers francais</option>

                    </select> </li>

            </ul>


        </form>
    </main>


</body>

</html>






<!----------------------traducteur.phtml------------------------------->


<
!DOCTYPE html >
    <
    html lang = "fr" >
    <
    head >
    <
    meta charset = "utf-8" >
    <
    title > PHP < /title> <
    link rel = "stylesheet"
href = "http://fonts.googleapis.com/css?family=Open+Sans" >
    <
    link rel = "stylesheet"
href = "05-exercice-traducteur.css" >
    <
    /head> <
    body >
    <
    header >
    <
    h1 > Traducteur Anglais - Français < /h1> <
    /header>

    <
    main >

    <
    form action = "traducteur.php"
method = "POST" >
    <
    ul >
    <
    li >
    <
    label
for = "word" > Mot: < /label> <
    input type = "text"
id = "word"
name = "word" >
    <
    /li> <
    li >
    <
    label
for = "direction" > Sens de traduction: < /label> <
    select id = "direction"
name = "direction" > //recupere valeur(donnee)
    <
    option value = "toEnglish" > Français vers Anglais < /option> <
    option value = "toFrench" > Anglais vers Français < /option> <
    /select> <
    /li> <
    li >
    <
    input type = "submit"
value = "Traduire" >
    <
    /li> <
    /ul> <
    /form>
<?php if($result != null) { ?>

<
p > <?= $result ?> < /p>

    <
    ?
} ? > // result = la valeur taper
<
/main> <
/body> <
/html>